export const PLATFORMS = [
  {
    id: "codility",
    name: "Codility",
    color: "#00c2ff",
    icon: "⚙",
    tagline: "Performance-scored. Every ms counts.",
    timeLimit: 30,
    focus: "Time & space complexity. Correctness + performance = full score.",
    categories: [
      "Arrays",
      "Sorting",
      "Prefix Sums",
      "Stacks & Queues",
      "Binary Search",
      "Dynamic Programming",
      "Greedy",
      "Graphs",
    ],
  },
  {
    id: "hackerrank",
    name: "HackerRank",
    color: "#00ea64",
    icon: "◆",
    tagline: "Domain-wide. Warm up then go deep.",
    timeLimit: 45,
    focus:
      "Broad coverage. Starts easy, ramps hard. Read constraints carefully.",
    categories: [
      "Warm-up",
      "Implementation",
      "Strings",
      "Sorting",
      "Search",
      "Graph Theory",
      "Recursion",
      "SQL",
    ],
  },
  {
    id: "testdome",
    name: "TestDome",
    color: "#ff6b35",
    icon: "◉",
    tagline: "Real-world C# scenarios.",
    timeLimit: 35,
    focus:
      "Practical code. LINQ, async, OOP, EF Core patterns. Not just puzzles.",
    categories: [
      "LINQ",
      "Async/Await",
      "OOP & Interfaces",
      "Collections",
      "Error Handling",
      "EF Core",
      "Design Patterns",
      "Unit Testing",
    ],
  },
  {
    id: "leetcode",
    name: "LeetCode",
    color: "#ffa116",
    icon: "◈",
    tagline: "FAANG gold standard.",
    timeLimit: 40,
    focus: "Optimal solutions. Know your data structures cold.",
    categories: [
      "Two Pointers",
      "Sliding Window",
      "Hash Maps",
      "Binary Search",
      "Trees",
      "Dynamic Programming",
      "Backtracking",
      "Graphs",
    ],
  },
  {
    id: "codesignal",
    name: "CodeSignal",
    color: "#bf7fff",
    icon: "⟡",
    tagline: "Arcade-style. Speed matters.",
    timeLimit: 20,
    focus: "Accuracy + speed = score. Start fast, don't choke on edge cases.",
    categories: [
      "Arcade",
      "Arrays",
      "Strings",
      "Matrix",
      "Sorting",
      "Bit Manipulation",
      "Math",
      "Linked Lists",
    ],
  },
  {
    id: "hackerearth",
    name: "HackerEarth",
    color: "#2196f3",
    icon: "◭",
    tagline: "Competitive-style problems.",
    timeLimit: 45,
    focus: "I/O heavy. Read stdin, write stdout. Edge cases are brutal.",
    categories: [
      "Basic Programming",
      "Arrays",
      "Strings",
      "Sorting",
      "Searching",
      "Trees",
      "Graphs",
      "Dynamic Programming",
    ],
  },
  {
    id: "coderbyte",
    name: "Coderbyte",
    color: "#ff4081",
    icon: "◫",
    tagline: "Company screening. Practical problems.",
    timeLimit: 30,
    focus: "Real company assessments. Mix of algorithms and practical tasks.",
    categories: [
      "Arrays",
      "Strings",
      "Objects",
      "File Parsing",
      "SQL Queries",
      "Regex",
      "OOP",
      "Recursion",
    ],
  },
  {
    id: "codewars",
    name: "Codewars",
    color: "#b22335",
    icon: "⛩",
    tagline: "Kata mastery. Community-driven.",
    timeLimit: 25,
    focus: "Elegant solutions rewarded. Think functional, think clean.",
    categories: [
      "Fundamentals",
      "Arrays",
      "Strings",
      "OOP",
      "Functional",
      "Algorithms",
      "Math",
      "Puzzles",
    ],
  },
];

export const LANGUAGES = [
  { id: "csharp", name: "C#", icon: "⬡", color: "#00ff88" },
  { id: "javascript", name: "JavaScript", icon: "JS", color: "#ffe066" },
  { id: "typescript", name: "TypeScript", icon: "TS", color: "#3178c6" },
  { id: "angular", name: "Angular", icon: "▲", color: "#dd0031" },
  { id: "sql", name: "SQL", icon: "⊞", color: "#ff9f00" },
];

export const DIFFICULTIES = [
  { id: "Easy", color: "#00ff88" },
  { id: "Medium", color: "#ff9f00" },
  { id: "Hard", color: "#ff5e7a" },
];
