import type { ScreeningCategory, ScreeningTypeOption } from "../types/domain";

export const SCREENING_CATEGORIES: ScreeningCategory[] = [
  {
    id: "csharp-dotnet",
    name: "C# & .NET Fundamentals",
    color: "#00ff88",
    icon: "⬡",
    topics: [
      "Value types vs Reference types",
      "IEnumerable vs IQueryable",
      "Abstract class vs Interface",
      "async/await & Task vs Thread",
      "LINQ & deferred execution",
      "Generics & constraints",
      "Delegates, Events, Func/Action",
      "Boxing/Unboxing",
      "Nullable types & pattern matching",
      "Dependency Injection lifetimes",
    ],
  },
  {
    id: "entity-framework",
    name: "Entity Framework & Data Access",
    color: "#bf7fff",
    icon: "⊞",
    topics: [
      "Code First vs Database First",
      "Lazy vs Eager vs Explicit loading",
      "Change tracker & entity states",
      "Migrations & seeding",
      "Repository pattern + Unit of Work",
      "Raw SQL vs LINQ performance",
      "DbContext lifetime & scoping",
      "Concurrency handling",
      "Query filters & soft deletes",
      "N+1 query problem",
    ],
  },
  {
    id: "sql-database",
    name: "SQL & Database Design",
    color: "#ff9f00",
    icon: "◆",
    topics: [
      "Normalization (1NF → BCNF)",
      "Indexes: clustered vs non-clustered",
      "Stored procedures vs inline queries",
      "Transaction isolation levels",
      "Execution plans & optimization",
      "Temp tables vs CTEs vs table variables",
      "JOINs: inner, outer, cross, self",
      "Window functions",
      "Deadlocks & locking strategies",
      "Database partitioning",
    ],
  },
  {
    id: "angular-frontend",
    name: "Angular & Frontend",
    color: "#dd0031",
    icon: "▲",
    topics: [
      "Lifecycle hooks (OnInit → OnDestroy)",
      "Change detection (Default vs OnPush)",
      "Observables vs Promises & RXJS",
      "Smart vs Dumb components",
      "Lazy loading modules & routes",
      "Dependency injection in Angular",
      "Template-driven vs Reactive forms",
      "Pipes: pure vs impure",
      "NgRx / state management",
      "Angular signals & zoneless",
    ],
  },
  {
    id: "api-architecture",
    name: "API & Architecture",
    color: "#00c2ff",
    icon: "⚙",
    topics: [
      "REST principles & HTTP status codes",
      "Microservices vs Monolith",
      "API versioning strategies",
      "JWT vs Cookies vs OAuth",
      "CORS — how it works",
      "Middleware pipeline (ASP.NET Core)",
      "CQRS & Event Sourcing",
      "Service Fabric / message queues",
      "Rate limiting & circuit breakers",
      "gRPC vs REST vs GraphQL",
    ],
  },
  {
    id: "design-patterns",
    name: "Design Patterns & SOLID",
    color: "#ffe066",
    icon: "◈",
    topics: [
      "SOLID principles with violations",
      "Factory, Strategy, Observer patterns",
      "Repository pattern — still worth it?",
      "Dependency Injection vs Service Locator",
      "Mediator pattern (MediatR)",
      "Decorator & Chain of Responsibility",
      "Singleton pitfalls in DI",
      "Clean Architecture layers",
      "Domain-Driven Design basics",
      "Anti-patterns in enterprise code",
    ],
  },
  {
    id: "code-review",
    name: "Code Review Challenges",
    color: "#ff5e7a",
    icon: "◫",
    topics: [
      "Controller action — find the issues",
      "LINQ query — why is it slow?",
      "Refactor this to follow SOLID",
      "Angular component — find the memory leak",
      "SQL query — fix the wrong results",
      "API endpoint — security vulnerabilities",
      "EF query — N+1 problem",
      "Async code — find the deadlock",
      "DI registration — lifetime mismatch",
      "Exception handling — what is wrong?",
    ],
  },
  {
    id: "data-modeling",
    name: "Data Modeling & System Design",
    color: "#2196f3",
    icon: "◭",
    topics: [
      "Design a payment processing schema",
      "Model a vehicle rental system",
      "JSON API response — redesign it",
      "Claims management data model",
      "User roles & permissions schema",
      "Event-driven order processing",
      "Multi-tenant database design",
      "Audit trail / history tracking",
      "Notification system architecture",
      "File upload & storage design",
    ],
  },
  /** Whiteboard + DevOps + tech-lead scenarios (senior / lead interviews). */
  {
    id: "whiteboard-system",
    name: "Whiteboard — System & Scale",
    color: "#a855f7",
    icon: "▭",
    topics: [
      "Sketch end-to-end request path (CDN → API → DB → cache)",
      "Design rate limiting for 50k RPS API",
      "Multi-region read/write strategy for banking profile data",
      "Real-time notifications at scale (fan-out, dedupe)",
      "File upload pipeline: resumable, virus scan, storage tiers",
      "Idempotency keys and exactly-once illusion at the board",
      "Read vs write path optimization (CQRS sketch)",
      "Session store: sticky vs shared state",
      "Background job queue vs stream processing — when which",
      "Capacity planning back-of-envelope for launch day",
    ],
  },
  {
    id: "devops-platform",
    name: "DevOps & Platform (SRE)",
    color: "#14b8a6",
    icon: "◇",
    topics: [
      "CI/CD for regulated releases: gates, evidence, sign-off",
      "Blue-green vs canary with database migrations",
      "Container image scanning — fail build vs warn",
      "K8s: Pod → Service → Ingress — explain traffic path",
      "Secrets: rotation, vault pattern, least privilege",
      "Incident response: first 15 minutes as incident commander",
      "SLO/SLI/SLA for an internal REST dependency",
      "Observability strategy for unknown-unknown outage",
      "IaC drift: detect, prevent, remediate",
      "Cost vs reliability levers you’d show leadership",
    ],
  },
  {
    id: "tech-leadership",
    name: "Tech Lead & Stakeholder situations",
    color: "#f472b6",
    icon: "◐",
    topics: [
      "PM cuts scope mid-sprint — how you respond in the room",
      "Two strong engineers disagree on architecture — facilitation",
      "Critical path depends on underperforming teammate",
      "Tech debt vs feature pressure — board-level framing",
      "Blameless postmortem: facilitation and action items",
      "Roadmap negotiation with product (evidence-based)",
      "On-call load unfair — structural fix as lead",
      "Mentoring plan for mid-level joining legacy monolith",
      "Cross-team dependency blocking release — escalation path",
      "Hiring bar: what you probe for senior vs staff in interview",
    ],
  },
];

/** First N categories are “classic” screening; rest are whiteboard / lead tracks. */
export const SCREENING_CORE_CATEGORY_COUNT = 8;

export const SCREENING_TYPES: ScreeningTypeOption[] = [
  { id: "concept", name: "Concept Comparison", icon: "💡", color: "#ffe066" },
  { id: "code_review", name: "Code Review", icon: "🔍", color: "#ff5e7a" },
  {
    id: "modeling",
    name: "Architecture / Modeling",
    icon: "🏗",
    color: "#00c2ff",
  },
  {
    id: "whiteboard_system",
    name: "Whiteboard — System design",
    icon: "▭",
    color: "#a855f7",
  },
  {
    id: "whiteboard_devops",
    name: "Whiteboard — DevOps / ops",
    icon: "◇",
    color: "#14b8a6",
  },
  {
    id: "whiteboard_lead",
    name: "Whiteboard — Lead / process",
    icon: "◐",
    color: "#f472b6",
  },
];

export const SCREENING_DIFFICULTIES: { id: string; color: string }[] = [
  { id: "Warm-up", color: "#00cfff" },
  { id: "Easy", color: "#00ff88" },
  { id: "Medium", color: "#ff9f00" },
  { id: "Hard", color: "#ff5e7a" },
];
