export const SCREENING_CATEGORIES = [
  {
    id: "csharp-dotnet",
    name: "C# & .NET Fundamentals",
    color: "#00ff88",
    icon: "⬡",
    topics: [
      "Value types vs Reference types",
      "IEnumerable vs IQueryable",
      "Abstract class vs Interface",
      "async/await & Task vs Thread",
      "LINQ & deferred execution",
      "Generics & constraints",
      "Delegates, Events, Func/Action",
      "Boxing/Unboxing",
      "Nullable types & pattern matching",
      "Dependency Injection lifetimes",
    ],
  },
  {
    id: "entity-framework",
    name: "Entity Framework & Data Access",
    color: "#bf7fff",
    icon: "⊞",
    topics: [
      "Code First vs Database First",
      "Lazy vs Eager vs Explicit loading",
      "Change tracker & entity states",
      "Migrations & seeding",
      "Repository pattern + Unit of Work",
      "Raw SQL vs LINQ performance",
      "DbContext lifetime & scoping",
      "Concurrency handling",
      "Query filters & soft deletes",
      "N+1 query problem",
    ],
  },
  {
    id: "sql-database",
    name: "SQL & Database Design",
    color: "#ff9f00",
    icon: "◆",
    topics: [
      "Normalization (1NF → BCNF)",
      "Indexes: clustered vs non-clustered",
      "Stored procedures vs inline queries",
      "Transaction isolation levels",
      "Execution plans & optimization",
      "Temp tables vs CTEs vs table variables",
      "JOINs: inner, outer, cross, self",
      "Window functions",
      "Deadlocks & locking strategies",
      "Database partitioning",
    ],
  },
  {
    id: "angular-frontend",
    name: "Angular & Frontend",
    color: "#dd0031",
    icon: "▲",
    topics: [
      "Lifecycle hooks (OnInit → OnDestroy)",
      "Change detection (Default vs OnPush)",
      "Observables vs Promises & RXJS",
      "Smart vs Dumb components",
      "Lazy loading modules & routes",
      "Dependency injection in Angular",
      "Template-driven vs Reactive forms",
      "Pipes: pure vs impure",
      "NgRx / state management",
      "Angular signals & zoneless",
    ],
  },
  {
    id: "api-architecture",
    name: "API & Architecture",
    color: "#00c2ff",
    icon: "⚙",
    topics: [
      "REST principles & HTTP status codes",
      "Microservices vs Monolith",
      "API versioning strategies",
      "JWT vs Cookies vs OAuth",
      "CORS — how it works",
      "Middleware pipeline (ASP.NET Core)",
      "CQRS & Event Sourcing",
      "Service Fabric / message queues",
      "Rate limiting & circuit breakers",
      "gRPC vs REST vs GraphQL",
    ],
  },
  {
    id: "design-patterns",
    name: "Design Patterns & SOLID",
    color: "#ffe066",
    icon: "◈",
    topics: [
      "SOLID principles with violations",
      "Factory, Strategy, Observer patterns",
      "Repository pattern — still worth it?",
      "Dependency Injection vs Service Locator",
      "Mediator pattern (MediatR)",
      "Decorator & Chain of Responsibility",
      "Singleton pitfalls in DI",
      "Clean Architecture layers",
      "Domain-Driven Design basics",
      "Anti-patterns in enterprise code",
    ],
  },
  {
    id: "code-review",
    name: "Code Review Challenges",
    color: "#ff5e7a",
    icon: "◫",
    topics: [
      "Controller action — find the issues",
      "LINQ query — why is it slow?",
      "Refactor this to follow SOLID",
      "Angular component — find the memory leak",
      "SQL query — fix the wrong results",
      "API endpoint — security vulnerabilities",
      "EF query — N+1 problem",
      "Async code — find the deadlock",
      "DI registration — lifetime mismatch",
      "Exception handling — what is wrong?",
    ],
  },
  {
    id: "data-modeling",
    name: "Data Modeling & System Design",
    color: "#2196f3",
    icon: "◭",
    topics: [
      "Design a payment processing schema",
      "Model a vehicle rental system",
      "JSON API response — redesign it",
      "Claims management data model",
      "User roles & permissions schema",
      "Event-driven order processing",
      "Multi-tenant database design",
      "Audit trail / history tracking",
      "Notification system architecture",
      "File upload & storage design",
    ],
  },
];

export const SCREENING_TYPES = [
  { id: "concept", name: "Concept Comparison", icon: "💡", color: "#ffe066" },
  { id: "code_review", name: "Code Review", icon: "🔍", color: "#ff5e7a" },
  {
    id: "modeling",
    name: "Architecture / Modeling",
    icon: "🏗",
    color: "#00c2ff",
  },
];

export const SCREENING_DIFFICULTIES = [
  { id: "Warm-up", color: "#00cfff" },
  { id: "Easy", color: "#00ff88" },
  { id: "Medium", color: "#ff9f00" },
  { id: "Hard", color: "#ff5e7a" },
];
